name: run buck builds and tests
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          submodules: 'true'
      - uses: dtolnay/install-buck2@latest
      - run: buck2 build //...
      
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          submodules: 'true'
      - uses: dtolnay/install-buck2@latest
      - run: 
          buck2 clean
          buck2 build //:py_install_venv
          buck2 test //...
          buck2 build //:py_uninstall_venv
      
